name: Ejecutar pruebas Jest

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x]

    steps:
    - name: Checkout código
      uses: actions/checkout@v4

    - name: Usar Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Instalar dependencias
      run: npm ci

    - name: Ejecutar pruebas
      run: npm test

    - name: Generar reporte de cobertura
      run: npm test -- --coverage

    # Opcional: Subir reporte de cobertura a Codecov
    - name: Subir cobertura a Codecov
      uses: codecov/codecov-action@v3
      with:
        fail_ci_if_error: false